// Catálogo completo de Regímenes Fiscales del SAT (México)
export const SAT_TAX_REGIMES: { code: string; label: string }[] = [
  { code: '601', label: '601 — General de Ley Personas Morales' },
  { code: '603', label: '603 — Personas Morales con Fines no Lucrativos' },
  { code: '605', label: '605 — Sueldos y Salarios e Ingresos Asimilados a Salarios' },
  { code: '606', label: '606 — Arrendamiento' },
  { code: '607', label: '607 — Régimen de Enajenación o Adquisición de Bienes' },
  { code: '608', label: '608 — Demás ingresos' },
  { code: '610', label: '610 — Residentes en el Extranjero sin Establecimiento Permanente en México' },
  { code: '611', label: '611 — Ingresos por Dividendos (socios y accionistas)' },
  { code: '612', label: '612 — Personas Físicas con Actividades Empresariales y Profesionales' },
  { code: '614', label: '614 — Ingresos por intereses' },
  { code: '615', label: '615 — Régimen de los ingresos por obtención de premios' },
  { code: '616', label: '616 — Sin obligaciones fiscales' },
  { code: '620', label: '620 — Sociedades Cooperativas de Producción que optan por diferir sus ingresos' },
  { code: '621', label: '621 — Incorporación Fiscal' },
  { code: '622', label: '622 — Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras' },
  { code: '623', label: '623 — Opcional para Grupos de Sociedades' },
  { code: '624', label: '624 — Coordinados' },
  { code: '625', label: '625 — Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas' },
  { code: '626', label: '626 — Régimen Simplificado de Confianza' },
];

// Catálogo completo de Uso de CFDI del SAT (México) - vigente 2024
export const SAT_CFDI_USES: { code: string; label: string; moral: boolean; fisica: boolean }[] = [
  { code: 'G01', label: 'G01 — Adquisición de mercancías', moral: true, fisica: true },
  { code: 'G02', label: 'G02 — Devoluciones, descuentos o bonificaciones', moral: true, fisica: true },
  { code: 'G03', label: 'G03 — Gastos en general', moral: true, fisica: true },
  { code: 'I01', label: 'I01 — Construcciones', moral: true, fisica: true },
  { code: 'I02', label: 'I02 — Mobiliario y equipo de oficina por inversiones', moral: true, fisica: true },
  { code: 'I03', label: 'I03 — Equipo de transporte', moral: true, fisica: true },
  { code: 'I04', label: 'I04 — Equipo de cómputo y accesorios', moral: true, fisica: true },
  { code: 'I05', label: 'I05 — Dados, troqueles, moldes, matrices y herramental', moral: true, fisica: true },
  { code: 'I06', label: 'I06 — Comunicaciones telefónicas', moral: true, fisica: true },
  { code: 'I07', label: 'I07 — Comunicaciones satelitales', moral: true, fisica: true },
  { code: 'I08', label: 'I08 — Otra maquinaria y equipo', moral: true, fisica: true },
  { code: 'D01', label: 'D01 — Honorarios médicos, dentales y gastos hospitalarios', moral: false, fisica: true },
  { code: 'D02', label: 'D02 — Gastos médicos por incapacidad o discapacidad', moral: false, fisica: true },
  { code: 'D03', label: 'D03 — Gastos funerales', moral: false, fisica: true },
  { code: 'D04', label: 'D04 — Donativos', moral: false, fisica: true },
  { code: 'D05', label: 'D05 — Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)', moral: false, fisica: true },
  { code: 'D06', label: 'D06 — Aportaciones voluntarias al SAR', moral: false, fisica: true },
  { code: 'D07', label: 'D07 — Primas por seguros de gastos médicos', moral: false, fisica: true },
  { code: 'D08', label: 'D08 — Gastos de transportación escolar obligatoria', moral: false, fisica: true },
  { code: 'D09', label: 'D09 — Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones', moral: false, fisica: true },
  { code: 'D10', label: 'D10 — Pagos por servicios educativos (colegiaturas)', moral: false, fisica: true },
  { code: 'S01', label: 'S01 — Sin efectos fiscales', moral: true, fisica: true },
  { code: 'CP01', label: 'CP01 — Pagos', moral: true, fisica: true },
  { code: 'CN01', label: 'CN01 — Nómina', moral: true, fisica: false },
];
